=== ShwetaKhera/1.45/clubServer/activityDataSchema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "https://www.drbsclasses.org/student49/node/info/example1.schema.json",
    "title": "Activity Data Schema",
    "description": "A Schema that requires a JSON object",
    "type": "object",
    "properties": {
        "date": {
            "type": "string",
            "pattern": "[0-9][0-9]/[0-9][0-9]/[0-9][0-9][0-9][0-9]"
        },
        "movie":{
            "type": "string",
            "minLength":1,
            "maxLength": 40
        },
        "description": {
            "type": "string",
            "maxLength": 300
        },
        "time": {
            "type": "string",
            "maxLength": 10
        }
    },
    "required": ["date", "movie","time"],
    "additionalProperties": false
  }

=== ShwetaKhera/1.45/clubServer/actDataTest1.json
{
    "date":"12/09/2020",
    "movie":"Harry Potter Series",
    "description":"Harry Potter is a film series based on the eponymous novels by author J. K. Rowling. The series is distributed by Warner Bros. and consists of eight fantasy films, beginning with Harry Potter and the Philosopher's Stone and culminating with Harry Potter and the Deathly Hallows â€“ Part 2.",
    "time":"20 hours"
  }

=== ShwetaKhera/1.45/clubServer/eventData.json
[
  {
    "date": "12/09/2020",
    "movie": "Harry Potter Series",
    "description": "Harry Potter is a film series based on the eponymous novels by author J. K. Rowling. The series is distributed by Warner Bros. and consists of eight fantasy films, beginning with Harry Potter and the Philosopher's Stone and culminating with Harry Potter and the Deathly Hallows â€“ Part 2.",
    "time": "20 hours"
  },
  {
    "date": "19/09/2020",
    "movie": "Iron Man",
    "description": "Iron Man is a fictional superhero appearing in American comic books published by Marvel Comics.",
    "time": "6 hours"
  },
  {
    "date": "26/09/2020",
    "movie": "The Hobbit",
    "description": "The Hobbit is a film series consisting of three high fantasy adventure films directed by Peter Jackson. They are based on the 1937 novel The Hobbit by J. R. R.",
    "time": "8.5 hours"
  }
]
